# Generated by Django 4.2.5 on 2023-09-16 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('codCarrinho', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('codCompra', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('formaPag', models.CharField(max_length=45)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codCarrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.carrinho')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('codItem', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Juridica',
            fields=[
                ('codPJ', models.AutoField(primary_key=True, serialize=False)),
                ('CNPJ', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('codPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=65)),
                ('Email', models.CharField(max_length=60)),
                ('Celular', models.CharField(max_length=18, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('codTransac', models.AutoField(primary_key=True, serialize=False)),
                ('codCompra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.compra')),
                ('codPJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.juridica')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valCashback', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perAtivac', models.CharField(max_length=45)),
                ('codItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.item')),
                ('codPJ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.juridica')),
            ],
        ),
        migrations.AddField(
            model_name='juridica',
            name='codPessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='juridica', to='cashbackapp.pessoa'),
        ),
        migrations.CreateModel(
            name='Itens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codCarrinho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.carrinho')),
                ('codItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Fisica',
            fields=[
                ('codPF', models.AutoField(primary_key=True, serialize=False)),
                ('CPF', models.PositiveIntegerField()),
                ('DataNASC', models.CharField(max_length=45)),
                ('saldoCash', models.CharField(max_length=45, null=True)),
                ('codPessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fisica', to='cashbackapp.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='carrinho',
            name='codPF',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashbackapp.fisica'),
        ),
    ]
