# Generated by Django 4.2.4 on 2023-10-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbackapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fisica',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='juridica',
            name='usuario',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
