# Generated by Django 4.2.4 on 2023-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbackapp', '0003_alter_fisica_datanasc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='descricao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
