# Generated by Django 4.2.5 on 2023-11-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbackapp', '0004_produtos_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='perAtivac',
            new_name='perPendentec',
        ),
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Enviado', 'Enviado'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
