# Generated by Django 4.2.5 on 2023-11-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbackapp', '0005_rename_perativac_produtos_perpendentec_compra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='status',
            field=models.CharField(choices=[('Em aberto', 'Em aberto'), ('Concluido', 'Concluido')], default='Em aberto', max_length=20),
        ),
    ]
